Update to Bazel 4.2 and rules_go 0.28
Fails to work with:

  $ bazel build :staticcheck-nogo-example
    ERROR: .../io_bazel_rules_nogo/BUILD.bazel:3:6: in alias rule @io_bazel_rules_nogo//:nogo: cycle in dependency graph:
      //:staticcheck-nogo-example
      @io_bazel_rules_go//:go_context_data
  .-> @io_bazel_rules_nogo//:nogo
  |   //tools/go:nogo
  |   @com_github_sluongng_staticcheck_codegen//_gen/sa1000:sa1000
  |   @co_honnef_go_tools//staticcheck:staticcheck
  |   @org_golang_x_tools//go/types/typeutil:typeutil
  |   @io_bazel_rules_go//:go_context_data
  `-- @io_bazel_rules_nogo//:nogo